# Generated by Django 4.1.7 on 2023-02-21 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('year', models.IntegerField(null=True)),
                ('still_active', models.BooleanField(null=True)),
                ('genre', models.IntegerField(choices=[(-1, 'Not Defined'), (0, 'Rock'), (1, 'Metal'), (2, 'Pop'), (3, 'Hip Hop'), (4, 'Electronic'), (5, 'Reggae'), (6, 'Other')], default=-1)),
            ],
        ),
    ]
