# Generated by Django 4.1.7 on 2023-02-21 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises_app', '0003_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('year', models.IntegerField()),
                ('rating', models.IntegerField(choices=[('', 'Zero'), ('*', 'One'), ('**', 'Two'), ('***', 'Three'), ('****', 'Four'), ('*****', 'Five')], max_length=5)),
            ],
        ),
    ]
