# Generated by Django 4.1.7 on 2023-02-21 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises_app', '0004_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='rating',
            field=models.CharField(choices=[('', 'Zero'), ('*', 'One'), ('**', 'Two'), ('***', 'Three'), ('****', 'Four'), ('*****', 'Five')], max_length=5),
        ),
    ]
