# Generated by Django 4.1.7 on 2023-02-22 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercises_app', '0006_album_band'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='band',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='exercises_app.band'),
            preserve_default=False,
        ),
    ]
