# Generated by Django 4.1.7 on 2023-03-03 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_movies', '0002_movie_personmovie_movie_starring'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personmovie',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='personmovie',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='personmovie',
            name='year',
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(to='manage_movies.genre'),
        ),
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
